### ISSUE TITLE
Controller interrupt doesn't restore TTY2OLED script

### ISSUE THREAD

**Issue by sigismond0** [mrchrisster/MiSTer_SAM#114]
When issuing a STOP command through terminal, TTY2OLED resumes normal functionality. But if SAM is interrupted by input, TTY2OLED remains stopped.

**Comment by mrchrisster** [comment]
Just updated the script. Since I can't test myself, does it work now?

**Comment by sigismond0** [comment]
Not fixed, and this appears to break SAM/TTY compatibility.  SAM still shuffles OK, but the TTY portion freezes after "stopping TTY2OLED.sh Done!", doesn't show a core countdown while monitoring, and shows a data transfer error on the screen.

**Comment by mrchrisster** [comment]
sorry, hard for me to debug since i don't have ttyoled. the only thing added here that affects ttyoled is a start command if you push a button. you're saying it's not working in general anymore?

**Comment by mrchrisster** [comment]
just updated the code again, using tty_exit function. does that make it better?

**Comment by sigismond0** [comment]
Does not appear to be fixed.  Game name remains on display after input interrupt, and TTY2OLED never brings up a new one if you switch cores.

Additionally, the TTY screen now appears to show the WELCOME TO SAM screen after a cold reboot.  So something's super broken now.  

Issuing the STOP command still works as expected, showing the GAME OVER screen and wiping back to the core graphic, TTY then works normally.    After issuing a STOP, TTY works fine after a reboot until SAM starts again.

(Deleted my previous comment, as I was testing without also making sure TTY was on current release.  These notes reflect my testing after your initial update about a half hour ago, and behavior is the same now).

**Comment by venice1200** [comment]
I tried exactly same things without success.
I think something kills the tty2oled starting process before a full start.

**Comment by mrchrisster** [comment]
My new tty2oled setup does not work with SAM at all (Devkit v4 device). I have to do some more tests on Monday as to why this happens...

**Comment by venice1200** [comment]
Means you have a working tty2oled display?

**Comment by mrchrisster** [comment]
Yes - and I'm excited it's finally working. After flashing with the Arduino software, the display never turned on so I assumed i either had a bad OLED display or dev board. As a last attempt after rechecking wires and reflashing for hours, I connected the dev board to my Mister and used `update_tty2oled.sh`. It updated the devkit and then started working immediately! Great stuff! Now I just have to figure out why it doesn't want to work with SAM at all. 
If tty2oled is disabled in SAM, it displays the images of the cores and everything works as expected. If it's enabled, it breaks functionality completely. So far I've not been able to even get one game info displayed. I see "Welcome to" at the top of the screen and then the message "cmdcls"in the middle of the screen...

**Comment by venice1200** [comment]
Disable SAM Autostart for a test.
If SAM starts before the tty2oled start it’s possible you get weites results.
Enable SAM debug to get some output drom the tty functions.
Did you change anything in the tty ini files?

**Comment by sigismond0** [comment]
That's the behavior I currently see whenever SAM is enabled, started with the update from yesterday.  "If you issue mister_sam_on.sh stop" it will kill SAM, show a GAME OVER screen, and restore regular TTY2OLED.  Then if  you use "mister_sam_on.sh start" it should run, show the "welcome to SAM" screen, start shuffling, and show core graphics followed by game names.  But if you just reboot or anything without issuing "mister_sam_on.sh stop", the TTY display seems to remain locked to SAM indefinitely and just kind of gums up as you describe.  

The release prior to this had expected behavior where TTY would work normally at boot, and SAM only takes over after it starts shuffling.  If you rebooted without issuing "mister_sam_on.sh stop" it would still reboot to a standard TTY state without SAM trying to take over immediately.Try rolling back your mister_sam_on.sh to the version from like a week ago and see how that behaves for you.  After all that time we spent in the forum thread, it was working great, so starting with that should give you a baseline of how it should look when working.

**Comment by venice1200** [comment]
Some thoughts...

USB Power:
My USB Hub uses VBUS control. 
Means, if I run a MiSTer reboot command via shell or press the reset button, my tty2oled device runs through a power cycle.
Some USB Hubs don't have VBUS control, means power stays at the ports all the time, even at resets.

Autostart:
tty2oled uses the MiSTer User-Startup function in "/media/fat/linux/user-startup.sh" since it was realized by Sorgelig 
which is triggered by "/etc/init.d/S99user" if i am right.
SAM uses "/etc/init.d/S93mistersam" which starts earlier than the user-startup/tty2oled autostart.

**Comment by mrchrisster** [comment]
That's probably it. I'm using an unpowered hub at the moment. I'll replace on Monday with a powered one and I will also change the startup procedure to use S99user. Cheers!

**Comment by mrchrisster** [comment]
Hmm, using a powered hub does not make a difference .. telling SAM to stop displays the Game Over screen but tty2oled than hangs. Could it have something to do with the Devkit v4 firmware maybe?

**Comment by venice1200** [comment]
All devices using the same firmware.
Only the the devices which using the Arduino ESP32dev Profile get code for a few more commands for the additional hardware (led,buzzer,sensor).
I have a lolin32 device for a test.

But your problem sounds like the same we had. The task to start the tty2oled daemon is killed before it could start.

I still have my last working SAM Version on my MiSTer, let me try this at first.
The only open point here was to start the tty2oled daemon after mouse/controller interact. Maybe the same problem?

USB:
A powered USB Hub helps only if you habe power delivery problems.
But my system reboots the tty2oled device if i hard reboot or reset the mister.
Depending on your autostart config this can make a difference in case of the commands sent to the tty2oled device.

**Comment by mrchrisster** [comment]
Just updated SAM to use the new startup method. Hope you are ok with me getting "inspired" by the way tty2ooled does it ;)
I got SAM working now with tty2ooled but I have to disable `function tty_waitforack` or else it hangs.

**Comment by venice1200** [comment]
I uploaded a new testing Version as my Lolin32 had the same issue.
See 
https://github.com/venice1200/MiSTer_tty2oled/wiki/Installation#testingoptional
how to get the testing Version.

Send a Private Forum Message as well.

**Comment by mrchrisster** [comment]
Thanks for the fix :) That seems to have done the trick. I re-enabled tty_waitforack and SAM works now. Yey!

**Comment by sigismond0** [comment]
Updated to test branches on both SAM and TTY2OLED, and things are looking better (but not perfect).  SAM does not take over TTY immediately after boot any longer.  SAM controls of TTY are looking good.  A few issues though:

TTY (on ESP32) now often comes up with a data transfer error immediately after a fresh boot or cold reboot.  Launching cores and soft rebooting to menu all show the graphics OK.  Don't know if this is related to the SAM timings or not, but it's much better than we had a couple of days ago.

**Interrupting with controller input does appear to restore TTY2OLED, just leaves the current display up until TTY refreshes from a trigger.  Kind of looks like it isn't restored, but if you soft reboot from menu you can see it working.**  

Skip command does cause a new game to come up with core graphic and game name, but also kills SAM script (monitor says it's not running) and leaves TTY2OLED dead as well.

MegaCD and TG16CD autoboot appear to be broken.  Is it possible the test branch has the same issue we found in main where it's mapped select instead of start for those two cores (and MegaCD might be capitalized wrong)?  I deleted all three mappings just to see what happens.  FDS works, with a new mapping being downloaded and text in monitor mode indicating the download.  TG16CD says it downloads a map in monitor and I see it in the config folder, but it does not boot through.  MegaCD does not say it downloads a map in monitor, and I do not see one in the folder.  (Just looked, there is no MegaCD map in test Github.  And if I pull in the TG16CD map from the main branch, it still does not work in test.)  Just wanted to report that here in case test gets migrated over again and something breaks!

**Comment by mrchrisster** [comment]
Thanks for your feedback!
The test branch of SAM is rather old, right now I'm doing all the changes to the main code. test branch doesn't have autoboot functionality. I haven't worked on restoring tty2oled functionality on button push. Interesting that it's kind of working with the old code...

One thing I observed with the new tty2oled code: It takes sometimes close to 20s longer to do the core switching now. If I disable tty2oled, it's instant.

One other exciting feature that's off-topic, I just implemented "No repeat" shuffle, meaning SAM will cycle through all your games once. No more seeing the same game all the time. This works for all folders with unzipped roms, not working for zipped archives yet...Since I test the releases here, I'll just keep pushing updates directly to main. testing branch will be used for major changes, like implementing mgl.

**Comment by sigismond0** [comment]
If SAM always takes over TTY2OLED right at boot, then TTY2OLED never works normally when SAM autorun is enabled.  You power up, see "Welcome to Super Attract Mode", but never see the MiSTer graphic, never see core graphics, etc.  It completely defeats the core purpose of TTY2OLED.  Please note that this behavior was not the case until the last few weeks when the new TTY2OLED code was put in to let SAM control it directly.  Previously, SAM would only take over once it actually started shuffling.  This should be the desired behavior--SAM only takes over TTY when SAM is actively using it.  If SAM is not currently shuffling, TTY2OLED should be left to run normally.

Testing skip command more, got several good skips, but then it started failing just as I described above. Failed twice in a row, then worked a few times.  Then failed.  Just kind of goes back and forth for me.  I think it may be related to issuing the skip right as a game is started.  If I let a game run for a good 15 seconds or so, it seems to always work.  Please see attached image for some errors seen in the monitor when skipping fails.

For button interrupt, it's a pretty minor thing, so no real rush on it.  Since the stop command works as expected, maybe it makes sense to align how the button press interrupt works with how the stop command works?

![Untitled](https://user-images.githubusercontent.com/51833276/162250605-c98d6cea-bf08-40ce-9c1a-8a3cc241befe.png)

**Comment by venice1200** [comment]
Before I add the code for full control the tty2oled behavior in SAM was a little bit out of control.
SAM was starting the function to write the text onto the display (for consoles) and let it run standalone using „&“.
This  function was now waiting for a change of /tmp/CORENAME to proceed.
SAM doesn‘t draw the picture as the tty2oled daemon is still active. A few seconds after the change of /tmp/CORENAME SAM starts to draw the text and finishes the function.
Means showing the picture was not in SAM‘s Hand. Some cores loading faster, some slower. Waiting for the change of /tmp/CORENAME can be working fine but showing picture and showing text comes from two different sources which can cause crazy results.

The function for Arcades was not using „&“ and works a bit different.

We need to figure out what is the better way.

If we go full control we need to make sure the tty2oled interface is configured before something is sent to the device.
If you use the SAM Autostart you may disable the tty2oled Autostart but in that case SAM needs to configure the device.

If we go the „old way“ without picture control we need to make sure the tasks don‘t go strange.

**Comment by venice1200** [comment]
Actually "full control" works fine for me. 

I am looking for the correct entry point after intrerrupting SAM by Mouse/Keyboard or Controller 
for the correct re-start of tty2oled.

**Comment by mrchrisster** [comment]
You have a good point Sigismund. Didn't think about "normal" operation, where the user just wants to play games.  I guess I've been working on SAM too much, no time for gaming anymore lol.
I'll look into why skip doesn't work when Autoboot is on, strange.

Finding the right entry point for ttyexit is tricky i know. I'll ask mellified if he can have a look since he wrote the button detection part.

**Comment by venice1200** [comment]
I am working on SAM functions where you can choose via INI variable 
if you like to use full tty2oled control (use "ack) or use the tty2oled daemon support (with sleeps).

**Comment by mrchrisster** [comment]
Great, I'll try this next week, thanks!
@Sigismund can you check if the newest SAM version works correct for skipping now?

**Comment by venice1200** [comment]
I have added “&” to the Arcades tty_update in the test version above.

**Comment by sigismond0** [comment]
@mrchrisster Skip not works correctly on BIOS cores when issued before the button press.  

Also is there a reason the ini says "tgfx16cd (not working with mgl)"?  It seems to work fine for me.  Or is TGFX16CD currently just set up not to use MGLs through SAM at all?

@venice1200 Tested your build, and I like the option.  You've nailed it on the pros and cons, so at least people can pick the version that works best for them.  Or maybe it might even make sense to just use ACK/old modes based on whether SAM has autoboot enabled or not, since that's the major breaking point.  Thoughts on that?  

Only issue I see right now is that when ttyuseack=no, there's some garbling of text (at least with the current TTY test branch).  See attached image.  Text looks fine when ttyuseack=yes.

![PXL_20220409_160127765 MP](https://user-images.githubusercontent.com/51833276/162582079-93f8adfa-cec4-4f0e-ab1e-acee7e29a187.jpg)

**Comment by venice1200** [comment]
This is overlapping output from both instances.
The text in the middle is output from the tty2oled Daemon, the other text is from SAM.
One Point more on "Cons" of "No = Old style Version"

**Comment by venice1200** [comment]
The "Testing Option" is only for us to test to see where the problems are located.

My opinion is actually to got the way of "full control".

**Comment by mrchrisster** [comment]
So I've been looking into SAM not restarting after button push and it has to do with SAM running in a tmux session. MCP gets called from within this session and closes when exit command is received. MCP is responsible for restarting SAM. 

@sigismond thanks, i updated the ini. That note is a leftover from when I first started implementing MGL support. 
Strange, skip is working for me correctly now for bios cores..

**Comment by sigismond0** [comment]
Oops, typo.  I meant "now works" and wrote "not works".  Skip before bios button press IS working.

**Comment by mrchrisster** [comment]
Well, that changes everything ;)

**Comment by venice1200** [comment]
Any idea where to attach code for the tty2oled start after an interruption?
If SAM is interrupted I see some text output. Where does this text come from?

And is autostart still an issue?

Happy eastern!

**Comment by sigismond0** [comment]
Yes, autostart with full control remains an issue unless there have been updates not mentioned here.  I did open up another issue for that, since it has been taking up so much thread space on this issue.

I think input interruption is resolved at this time.  It's just tricky because it doesn't actually look like it restarted, even though it did--since TTY only updates on core change, you still see the SAM game text on screen even after TTY is running again.  You aren't actually be able to tell that TTY is running without soft resetting back to the menu or otherwise changing cores.  But as of last time I tested, it is working.

**Comment by mrchrisster** [comment]
Yeah i fixed MCP being shut down by the main script but am currently changing a couple other things as well. I should have more time next week to weave it all together.

**Comment by mrchrisster** [comment]
Would you mind updating and checking if SAM restarts now after a button was pushed?
If you set menuonly=no in `MiSTer_SAM.ini` it should restart after a button push now. Thanks!

**Comment by mrchrisster** [comment]
SAM restarting after button push is now fixed. I'm back in the office (with my tty2oled setup) and should have some time this week to look into this.

**Comment by mrchrisster** [comment]
Just integrated the script venice posted to the latest SAM main.

**Comment by mrchrisster** [comment]
I can't get arcade mode to work with the newest script unfortunately

**Comment by venice1200** [comment]
Try
`tty_update "${CORE_PRETTY[${nextcore,,}]}" "${mraname}" "${mrasetname}" &`
with the & at the end.

**Comment by mrchrisster** [comment]
That was it, thanks! I'll let this run for a few days and see if anything needs improvement.

**Comment by venice1200** [comment]
You forgot the "ttyuseack" Option the INI which is responsible to enable "full controll".
The standard setting in MiSTer_SAM_on.sh is `ttyuseack="no"`

Should I test "full control" or the other functionality?

**Comment by mrchrisster** [comment]
Ah thanks, I'll fix that.
Now that MCP is running externally, full control might work just as well. If you would like to let full control run, I'll let passive mode run here for a few days.

**Comment by venice1200** [comment]
Note, I saw bigger issues using an 8266 without "ACK". 
The screen looks similar to the picture from above from sigismond0.
With "ACK" everything runs smooth.

This is because of the speed of the system. 
Everything needs a longer time and sometimes the "sleep" in "waitforack" is not long enough and two commands overlapping.

**Comment by mrchrisster** [comment]
Sounds good, we'll leave ack on for now as a default then

**Comment by sigismond0** [comment]
The only real outstanding issue with ACK is that if you have SAM autoplay enabled in the ini, it kills the main TTY2OLED script immediately at boot time, preventing TTY2OLED from working normally even though SAM isn't actually shuffling.  Is there any reason that ACK mode couldn't wait for SAM's idle timeout before killing TTY and taking over the display?

**Comment by venice1200** [comment]
If SAM waits a while after boot before the tty2oled Daemon is killed, that should help, or not?
Or check for a running tty2oled Daemon and then wait a few seconds.

**Comment by mrchrisster** [comment]
I'm not near my Mister atm, but what if you set SAMTIMEOUT to let's say 2 mins. Does it still kill the daemon at startup or when SAM starts?

**Comment by venice1200** [comment]
The Daemon is killed from ttyinit in MiSTer_SAM_on.sh.
Just call it later.

To get the earliest moment to kill the tty daemon, check for his pid and check /tmp/CORENAME for „MENU“. 
If these two checks are Ok wait a few seconds and kill the daemon.

**Comment by sigismond0** [comment]
Correct, no matter what SAMTIMEOUT is set to, TTY is always killed immediately after boot with ACK is enabled.  Spounds like Venice already has you pointed in the right direction.

**Comment by mrchrisster** [comment]
@venice1200 Could you do a PR?

**Comment by venice1200** [comment]
PR?
I don‘t know about SamTimeout.

**Comment by mrchrisster** [comment]
Ok, I'll see where tty_init will make the most sense. Sorry,  I assumed you had a plan where to put it..

**Comment by venice1200** [comment]
Not really. I would have to search too!

**Comment by mrchrisster** [comment]
I don't think samtimeout or tty_init are the issue here. The problem seems to be that during bootup, the clock of the Mister gets set once Internet connection is established. 
SAM thinks the files it has created during bootup with a timestamp from 1970 are suddenly 30 odd years old and it better starts showing some roms now!
I fixed this by adding a 1 min delay to SAM's startup which should provide adequate time for clock synchronization. 
@sigismond0 Can you update and test if this works correctly now?

**Comment by mrchrisster** [comment]
SAM seems to start even when you are not in the main menu which is a bug and I'm currently not sure why it's doing this.
Quick feedback on tty2oled. During my testing I've had a lot of issues with `Stopping tty2oled ScreenSaver...`
tty2oled hangs here and even a reboot can't fix it. Need to hard reset.

**Comment by mrchrisster** [comment]
I think I got it fixed now!

**Comment by mrchrisster** [comment]
Btw, your ini should now update as well but will keep the values you set

**Comment by sigismond0** [comment]
Did some quick testing this morning, and SAM no longer kills TTY/queues shuffling while in a core.

TTYUSEACK, however, now seems to be broken.  Instead of displaying core graphics, it just says the core name in plain text.  Everything else (game names, transitions, etc) seems to work, just the graphics are broken.  

Additionally TTY is no longer restored when shuffling is interrupted by button presses.  SAM ends gracefully and puts the main MiSTer graphic on the screen, but doesn't restore TTY.

**Comment by mrchrisster** [comment]
Thanks for testing. tty_init was initialized too early. I can't test but just updated the code. Hopefully it works now.

**Comment by sigismond0** [comment]
Yep, graphics now show correctly while shuffling.  

TTY is still not restored after controller input stops SAM.

**Comment by sigismond0** [comment]
Yes, SAM looks like it's exiting and doing the cleanup step of sending the MiSTer graphic.  But after that, if you go go launch another core it just stays on that MiSTer graphic indefinitely.  (Unless SAM shuffles again, in which case it works for SAM as expected.)

**Comment by mrchrisster** [comment]
Does stop command restore tty?

**Comment by sigismond0** [comment]
So after some repeated attempts, it looks like I'm getting inconsistent results.

About half the time, I get the MiSTer graphic, but TTY is not restored.  Another half of the time, TTY is just left solid black.  Exactly one time I got TTY to actually be restored.

Watching in Monitor, sometimes it just kind of hangs right after it says "controller activity detected", and that's when the display is left blank.  If it doesn't hang at that point, the MiSTer graphic is put on display, but TTY isn't restored.

Similar results when using the stop command, though that throws an error too.  Sometimes it hangs after the error line, and TTY display is left blank.  Sometimes it continues through and TTY display shows the MiSTer graphic.

```
/root# mister_sam_on.sh start
 Stopping other running instances of mister_sam_on.sh... Done!
 Starting SAM in the background.
/root# mister_sam_on.sh stop
/media/fat/Scripts/mister_sam_on.sh: line 806: sam_stop: command not found
```

**Comment by venice1200** [comment]
Let me know when the SAM Logic works as it should be.
If you then still have tty2oled issues I will look into.

Question, if SAM is running and a key or a button is pressed, SAM goes into something like a sleep/wait mode. 
It's not finished, correct?

**Comment by mrchrisster** [comment]
So SAM is basically two scripts running. MCP checks if you are in menu core and how much time has passed since last button input. If both conditions are true, MiSTer_SAM_on will be launched. If a button is pushed, MiSTer_SAM_on will exit.

**Comment by mrchrisster** [comment]
Menuonly means only start SAM if corename is menu. If `menuonly=No` than SAM will also start while other cores are launched

**Comment by mrchrisster** [comment]
Logic should be correct now. On bootup, only MCP gets launched now. Before, MiSTer_SAM_on was also launched, which caused SAM to start even when core wasn't menu. I'd appreciate if you can look into tty_exit function. Not sure why Mister logo gets restored but tty2oled doesn't come back to life otherwise

**Comment by venice1200** [comment]
> So SAM is basically two scripts running. MCP checks if you are in menu core and how much time has passed since last button input. If both conditions are true (samtimeout has passed and corename is menu), MiSTer_SAM_on will be launched. If a button is pushed, MiSTer_SAM_on will exit.

Means only the MCP will be started from MiSTer's Autostart.
THX

**Comment by venice1200** [comment]
How is the actual overall status with the tty2oled integration?

Generally we have a few tty2oled issues.
tty2oled with ESP8266 is much slower than the tty2oled with ESP32.
Means all settings related to "sleeps" and "Daemon Mode" must be adjusted for the slowest tyt2oled hardware.
I still use ACK with my ESP32 and it works nice.
I can add timeouts for not stopping SAM but this doesn't eleminate the problem.

I am just running tests with an 8266 and I have to adjust the sleep in tty_waitfor a lot.
Generally we have to make sure that a new command is only sent to the display 
when the previous command is completely finished.

**Comment by mrchrisster** [comment]
Thanks for describing the problem. Ack mode works well so that probably still is our best bet. I was tinkering around some more trying to get ack working in SAM yesterday.
I'm thinking of putting MCP in control of exiting `MiSTer_SAM_on.sh`. We might have to revamp how SAM works to integrate tty2oled cleanly

**Comment by mrchrisster** [comment]
One of the issues seems to be that `echo "CMDCLST,-1,0" >${ttydevice}` blocks SAM from exiting if the command doesn't succeed. I've run into this a couple of times

**Comment by venice1200** [comment]
Hi,
It looks to me that „ack“ is completely not in use as everything related to read data from tty2oled is commented out.

Or did you rewrite it?

**Comment by mrchrisster** [comment]
Yeah, I commented out ack yesterday evening while testing some stuff because it kept preventing SAM from exiting. I'll change it back now

**Comment by venice1200** [comment]
Line 2249, one # too much removed 😃

**Comment by venice1200** [comment]
One Note to SAM Autostart.
I re-installed my i2c2oled and my setup procedure set the autostart after the SAM line.
Now i2c2oled starts after the init of SAM and not directly.
If I set the i2c2oled autostart before SAM or deactivate SAM Autostart everything is OK.

Means, every Autostart-Script after SAM is delayed for the Time 
`/media/fat/Scripts/.MiSTer_SAM/MiSTer_SAM_init` needs to run.

**Comment by venice1200** [comment]
I upodated my SAM Installation adn is is wokring fine, also with the 8266.
What exactly should I test or look for?

**Comment by mrchrisster** [comment]
> Line 2249, one # too much removed 😃

Fixed, thanks!
For Autostart, what's the best way to make sure i2c2oled runs before SAM? Do you want to add a check to the install script?

Since you are not using button detection, i expect it to work fine for your use case. If SAM could tell the tty2oled daemon to sleep while SAM is running, SAM would not need to manage it's startup (which is currently the problem)

**Comment by venice1200** [comment]
MiSTer Autostart:
You have to make sure your entry in `/media/fat/linux/user-startup.sh` doesn't block any Script behind.
I think a simple "&" could help.
Since the beginning we use our S60 Script which starts the tty2oled damon with "&" and finishes.
If someone else adding something behind your Start Script he will wonder why it's not correctly started at boot 
and need a delay.

::If SAM could tell the tty2oled daemon to sleep
But thats exactly what we are doing at the moment. 
We stop the Daemon at SAM's **"start_real"** and we start it again at SAM **"stop"**.
That should work, or not?

The tty2oled daemon is not the problem.
The Problem is to make the SAM Script working together with all hardware version of tty2oled.
An ESP32 needs a lot less time to show a Core Picture on the Screen than a 8266. The same for text output. 
So "full control" is in my eye's the best option we have as this works independent of the hardware.

I have tested the past days without "ack" and I had to increase the responsibe "sleep" from 0.05 to 0.45 seconds to get it working with a 8266 tty2oled display. That's a big difference. And finally not stable enough.
Antonio is one of the bigger MiSTer Sellers and he sells tty2oled devices with 8266 MCU's.

=========================================================
Questions:

SAM-Start:
Is MiSTer_SAM_on.sh started by the MCP on Autostart after the boot delay and after a Keyboard/Joystick timeout?
If yes, you can stop the tt2oled daemon from the MCP.

Button detection:
Is MiSTer_SAM_on.sh killed completely by the MCP when a button was detected?
If yes, you can start the tt2oled daemon from the MCP.

MCP:
Is the MCP also startet when I run **MiSTer_SAM_on.sh start** by hand?

Do you have something like a MiSTer_SAM flowchart to see which function is called when soemthing happens?

**Comment by venice1200** [comment]
Maybe a few of my comments are already realized.
SAM was started from the Autostart and after I pressed the button to the Core Picture was shown.

**Comment by venice1200** [comment]
Is starting SAM manually using "start" and waiting for SAM's Autostart the same?

**Comment by mrchrisster** [comment]
yep, both use start

**Comment by venice1200** [comment]
Hi,
OK.

You (re) start tty2oled at 2 places. I don't know if both are used but..

MiSTer_SAM_on.sh
1) https://github.com/mrchrisster/MiSTer_SAM/blob/0f54aa838c93a3e5a56de7ccf8daf916fe8222ce/MiSTer_SAM_on.sh#L2289
This one should should use **/media/fat/tty2oled/S60tty2oled start** instead of **tty2oled.sh**

And the second in the MCP
2) https://github.com/mrchrisster/MiSTer_SAM/blob/ec8caba2ca7e66db73b1eca600a93bf27cc0a5db/.MiSTer_SAM/MiSTer_SAM_MCP#L36

**Comment by venice1200** [comment]
Please make sure only one is used.

**Comment by mrchrisster** [comment]
Number 1 didn't work when I called `/media/fat/tty2oled/S60tty2oled start` in a tmux session
Number 2 was a test if it makes any difference starting from MCP, it's not called and will be taken out.

**Comment by mrchrisster** [comment]
As previously stated, I think the better way would be to not start or kill your daemon at all.
Something like `/media/fat/tty2oled/S60tty2oled pause` and `/media/fat/tty2oled/S60tty2oled continue`

**Comment by mrchrisster** [comment]
slower eactions are due to usedefaultpaths="Yes" in the ini. This should be `usedefaultpaths="No"`

**Comment by venice1200** [comment]
Ok

**Comment by venice1200** [comment]
I don't understand "Stop" of SAM.

The "&" here
https://github.com/mrchrisster/MiSTer_SAM/blob/3733d0237342cce2d9f213f5de698199cef51203/MiSTer_SAM_on.sh#L2279
should not be neccessary.

Is it possible that anything stops MiSTer_SAM_on.sh before "tty_exit" is processed completely?

**Comment by mrchrisster** [comment]
To answer your question:
It was rather the opposite. SAM wouldn't exit all if tty_exit was processed.

**Comment by venice1200** [comment]
> I have to admit, I don't fuly understand tty_waitfor either ;) I just figured out it was the culprit in making SAM exit cleanly. Maybe with killing the while loop, we can omit the `&`, i'll check

Weird as there are no special commands.
tty_waitfor does nothing more than starts to read and wait (now max. 10s) for an response of the tty2oled display.
It's like waitung for an keyboard input.

The tty2oled display sends the string "ttyack;" back to the MiSTer after the MCU has processed.

**Comment by venice1200** [comment]
I am testing the "Daemon Mode" and found some issues.

As I told you the 8266 is a lot slower than the ESP32.
In "tty_update" is a 7 second delay between the Logo and the text.
https://github.com/mrchrisster/MiSTer_SAM/blob/de4040953b906197b72d4b1ab8e5e0b9b377bb4e/MiSTer_SAM_on.sh#L2363
Depending on the transition which is used to clear the screen after the logo is shown, 7 seconds can be too less and we get a command override (which is not possible using "ACK").
I set the sleep to 10 seconds for testing which should be OK for the ESP8266.
We can make it shorter if we use no or a faster transition here.

Another sleep which need to adjusted for the 8266 is here.
https://github.com/mrchrisster/MiSTer_SAM/blob/de4040953b906197b72d4b1ab8e5e0b9b377bb4e/MiSTer_SAM_on.sh#L2341
0.05 is working for the ESP32. I am testing succesful a value of 0.4 with the 8266.

**Comment by venice1200** [comment]
It possible we need to cut the second text line to 20 characters as well.
https://github.com/mrchrisster/MiSTer_SAM/blob/de4040953b906197b72d4b1ab8e5e0b9b377bb4e/MiSTer_SAM_on.sh#L2375

**Comment by venice1200** [comment]
Is there a difference within SAM calling **sam_exit** or **sam_stop**.
Both run `echo "load_core /media/fat/menu.rbf" >/dev/MiSTer_cmd`

What is the best function to call "S60tty2oled start" if I like to test "full control".

**Comment by venice1200** [comment]
Is this OK?
![2022-05-27 13_20_21-MiSTer2 (192 168 0 75)](https://user-images.githubusercontent.com/43762187/170690083-56acf1f3-c312-4ee5-8bdb-a811517c17b9.png)

**Comment by venice1200** [comment]
The next round was working fine!

**Comment by mrchrisster** [comment]
Wow, crazy. How did you manage to start all these processes :O
Thanks for explaining tty_waitfor. It makes sense, what I meant was i don't understand the response timing since I didn't look into how tty2oled works in detail.
I'll be gone for ten days, but will push your updates so other people like Sigismond can test the changes.
Cheers!

**Comment by Paradox** [comment]
Sam_stop kills everything, sam_exit, does some cleanup, and exits, leaving mcp, etc running, so it can automatically start running again, after the wait time.

**Comment by Paradox** [comment]
> Is there a difference within SAM calling **sam_exit** or **sam_stop**. Both run `echo "load_core /media/fat/menu.rbf" >/dev/MiSTer_cmd`

Sam_stop kills everything, sam_exit, does some cleanup, and exits, leaving mcp, etc running, so it can automatically start running again, after the wait time.

**Comment by Paradox** [comment]
I have a kit, on its way, and, I will also be able to start testing, soon.

**Comment by venice1200** [comment]
> Sam_stop kills everything, sam_exit, does some cleanup, and exits, leaving mcp, etc running, so it can automatically start running again, after the wait time.

When is same_exit used, when sam_stop?

**Comment by venice1200** [comment]
> ... but will push your updates so other people like Sigismond can test the changes. Cheers!
So my changes are already in your Repo?

**Comment by mrchrisster** [comment]
Yep, changes are in the repo!
sam_stop is only used when you issue `MiSTer_SAM_on.sh stop`
It kills all SAM related processes so basically disables it until restart. 

sam_exit is implemented by Paradox, it currently reloads the menu core but i believe he's working in some changes to that

**Comment by venice1200** [comment]
To show the last loaded picture on the tty2oled display
use CMDSPIC.

https://github.com/venice1200/MiSTer_tty2oled/wiki/Command_v2#command-cmdspic

Maybe helpful for the Daemon Mode.

**Comment by venice1200** [comment]
Correct me if I am wrong.

I thought, if you touch a button/keyboard/mouse during SAM is running the actual running game can be played.
And if you wait a while, without touching button/keyboard/mouse, SAM starts running again.

Is this correct?
If yes, which "sam_" function is called in this case?

**Comment by venice1200** [comment]
Related to CMDSPIC

A "CMDCLST" before clears the Picture Buffer and you get a empty screen.
https://github.com/mrchrisster/MiSTer_SAM/blob/07cdc3706309527da491d2f4a2f3550a3601d147/MiSTer_SAM_on.sh#L2373

So we have to replace "CMDCLST" with "CMDCLS" or "CMDCLSWU".
These two commands clearing only the Displays Screen Buffer himself and don't touch the tty2oled Picture Buffer.

**Comment by mrchrisster** [comment]
> Correct me if I am wrong.
> 
> I thought, if you touch a button/keyboard/mouse during SAM is running the actual running game can be played. And if you wait a while, without touching button/keyboard/mouse, SAM starts running again.
> 
> Is this correct? If yes, which "sam_" function is called after a button/keyboard/mouse was touched?

https://github.com/mrchrisster/MiSTer_SAM/blob/main/MiSTer_SAM_on.sh#L2591

play_or_exit closes SAM on button push. On restart MCP starts SAM again

**Comment by mrchrisster** [comment]
> 

CMDCLSWU is now enabled and CMDCLST disabled

**Comment by venice1200** [comment]
> > 
> 
> CMDCLSWU is now enabled and CMDCLST disabled

There is another one in 
https://github.com/mrchrisster/MiSTer_SAM/blob/062c59e2e9ddaadd098556df21f55dd457cd132d/MiSTer_SAM_on.sh#L2443

**Comment by mrchrisster** [comment]
I changed everything to CMDCLS

**Comment by mrchrisster** [comment]
This seems to be resolved
